/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VedicAutoMatch {
  export type MatchStruct = {
    id: BigNumberish;
    profileA: BigNumberish;
    profileB: BigNumberish;
    state: BigNumberish;
    encryptedScore: BytesLike;
    createdAt: BigNumberish;
    consentedA: BigNumberish;
    consentedB: BigNumberish;
  };

  export type MatchStructOutput = [
    id: bigint,
    profileA: bigint,
    profileB: bigint,
    state: bigint,
    encryptedScore: string,
    createdAt: bigint,
    consentedA: bigint,
    consentedB: bigint
  ] & {
    id: bigint;
    profileA: bigint;
    profileB: bigint;
    state: bigint;
    encryptedScore: string;
    createdAt: bigint;
    consentedA: bigint;
    consentedB: bigint;
  };
}

export interface VedicAutoMatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "consentToReveal"
      | "createProfile"
      | "getMatch"
      | "getMyProfileData"
      | "matches"
      | "nextMatchId"
      | "nextProfileId"
      | "onDecryptionFulfilled"
      | "profiles"
      | "submitMatchScore"
      | "updateMatchState"
      | "userProfiles"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchCreated"
      | "MatchScoreSubmitted"
      | "MatchStateChanged"
      | "ProfileCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "consentToReveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProfile",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyProfileData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMatchId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextProfileId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onDecryptionFulfilled",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitMatchScore",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMatchState",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userProfiles",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "consentToReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMyProfileData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextProfileId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onDecryptionFulfilled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitMatchScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMatchState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProfiles",
    data: BytesLike
  ): Result;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    profileA: BigNumberish,
    profileB: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    profileA: bigint,
    profileB: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    profileA: bigint;
    profileB: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchScoreSubmittedEvent {
  export type InputTuple = [matchId: BigNumberish, encryptedScore: BytesLike];
  export type OutputTuple = [matchId: bigint, encryptedScore: string];
  export interface OutputObject {
    matchId: bigint;
    encryptedScore: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchStateChangedEvent {
  export type InputTuple = [matchId: BigNumberish, newState: BigNumberish];
  export type OutputTuple = [matchId: bigint, newState: bigint];
  export interface OutputObject {
    matchId: bigint;
    newState: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileCreatedEvent {
  export type InputTuple = [profileId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [profileId: bigint, owner: string];
  export interface OutputObject {
    profileId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VedicAutoMatch extends BaseContract {
  connect(runner?: ContractRunner | null): VedicAutoMatch;
  waitForDeployment(): Promise<this>;

  interface: VedicAutoMatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consentToReveal: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProfile: TypedContractMethod<
    [_encryptedName: BytesLike, _encryptedHandle: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [VedicAutoMatch.MatchStructOutput],
    "view"
  >;

  getMyProfileData: TypedContractMethod<
    [profileId: BigNumberish],
    [[string, string]],
    "view"
  >;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        profileA: bigint;
        profileB: bigint;
        state: bigint;
        encryptedScore: string;
        createdAt: bigint;
        consentedA: bigint;
        consentedB: bigint;
      }
    ],
    "view"
  >;

  nextMatchId: TypedContractMethod<[], [bigint], "view">;

  nextProfileId: TypedContractMethod<[], [bigint], "view">;

  onDecryptionFulfilled: TypedContractMethod<
    [
      matchId: BigNumberish,
      decryptedNameA: BytesLike,
      decryptedHandleA: BytesLike,
      decryptedNameB: BytesLike,
      decryptedHandleB: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  profiles: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        owner: string;
        encryptedName: string;
        encryptedHandle: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  submitMatchScore: TypedContractMethod<
    [profileA: BigNumberish, profileB: BigNumberish, encryptedScore: BytesLike],
    [bigint],
    "nonpayable"
  >;

  updateMatchState: TypedContractMethod<
    [matchId: BigNumberish, newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  userProfiles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consentToReveal"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createProfile"
  ): TypedContractMethod<
    [_encryptedName: BytesLike, _encryptedHandle: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [VedicAutoMatch.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyProfileData"
  ): TypedContractMethod<[profileId: BigNumberish], [[string, string]], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        profileA: bigint;
        profileB: bigint;
        state: bigint;
        encryptedScore: string;
        createdAt: bigint;
        consentedA: bigint;
        consentedB: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMatchId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextProfileId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onDecryptionFulfilled"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      decryptedNameA: BytesLike,
      decryptedHandleA: BytesLike,
      decryptedNameB: BytesLike,
      decryptedHandleB: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        owner: string;
        encryptedName: string;
        encryptedHandle: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitMatchScore"
  ): TypedContractMethod<
    [profileA: BigNumberish, profileB: BigNumberish, encryptedScore: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMatchState"
  ): TypedContractMethod<
    [matchId: BigNumberish, newState: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchScoreSubmitted"
  ): TypedContractEvent<
    MatchScoreSubmittedEvent.InputTuple,
    MatchScoreSubmittedEvent.OutputTuple,
    MatchScoreSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "MatchStateChanged"
  ): TypedContractEvent<
    MatchStateChangedEvent.InputTuple,
    MatchStateChangedEvent.OutputTuple,
    MatchStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileCreated"
  ): TypedContractEvent<
    ProfileCreatedEvent.InputTuple,
    ProfileCreatedEvent.OutputTuple,
    ProfileCreatedEvent.OutputObject
  >;

  filters: {
    "MatchCreated(uint256,uint256,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchScoreSubmitted(uint256,bytes32)": TypedContractEvent<
      MatchScoreSubmittedEvent.InputTuple,
      MatchScoreSubmittedEvent.OutputTuple,
      MatchScoreSubmittedEvent.OutputObject
    >;
    MatchScoreSubmitted: TypedContractEvent<
      MatchScoreSubmittedEvent.InputTuple,
      MatchScoreSubmittedEvent.OutputTuple,
      MatchScoreSubmittedEvent.OutputObject
    >;

    "MatchStateChanged(uint256,uint8)": TypedContractEvent<
      MatchStateChangedEvent.InputTuple,
      MatchStateChangedEvent.OutputTuple,
      MatchStateChangedEvent.OutputObject
    >;
    MatchStateChanged: TypedContractEvent<
      MatchStateChangedEvent.InputTuple,
      MatchStateChangedEvent.OutputTuple,
      MatchStateChangedEvent.OutputObject
    >;

    "ProfileCreated(uint256,address)": TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;
    ProfileCreated: TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;
  };
}
